{% macro main(rule) %}
# DIRECT

// Client
PROCESS-NAME,Paws for Trello,{{ rule }}
PROCESS-NAME,ss-local,{{ rule }}
PROCESS-NAME,Thunder,{{ rule }}
PROCESS-NAME,DownloadService,{{ rule }}
PROCESS-NAME,TeamViewer,{{ rule }}
PROCESS-NAME,trustd,{{ rule }}
PROCESS-NAME,WebTorrent,{{ rule }}
PROCESS-NAME,WeChat,{{ rule }}

// UA
USER-AGENT, %E4%BA%AC%E4%B8%9C%E5%88%B0%E5%AE%B6*,{{ rule }}
USER-AGENT,%E5%8D%B3%E5%88%BB*,{{ rule }}
USER-AGENT,*Vainglory* ,{{ rule }}
USER-AGENT,AdBlock*,{{ rule }}
USER-AGENT,arrowio*,{{ rule }}
USER-AGENT,balls*,{{ rule }}
USER-AGENT,Beplay*,{{ rule }}
USER-AGENT,Best%20Trace*,{{ rule }}
USER-AGENT,cmblife*,{{ rule }}
USER-AGENT,eusoft_ting_en_iphone,{{ rule }}
USER-AGENT,hide*,{{ rule }}
USER-AGENT,JDLife*,{{ rule }}
USER-AGENT,LastPass*,{{ rule }}
USER-AGENT,MegaWerewolf*,{{ rule }}
USER-AGENT,MicroMessenger*,{{ rule }}
USER-AGENT,Microsoft*,{{ rule }}
USER-AGENT,Moke*,{{ rule }}
USER-AGENT,osee2unifiedRelease*,{{ rule }}
USER-AGENT,PayPal*,{{ rule }}
USER-AGENT,QQ*,{{ rule }}
USER-AGENT,Speedtest*,{{ rule }}
USER-AGENT,TeamViewer*,{{ rule }}
USER-AGENT,TIM*,{{ rule }}
USER-AGENT,ting_en,{{ rule }}
USER-AGENT,WebTorrent*,{{ rule }}
USER-AGENT,WeChat*,{{ rule }}

// Beplay
DOMAIN-KEYWORD,beplay,{{ rule }}

// Blizzard
USER-AGENT,Blizzard*,{{ rule }}
USER-AGENT,wowcompanion*,{{ rule }}
DOMAIN-SUFFIX,battle.net,{{ rule }}
DOMAIN-SUFFIX,battlenet.com,{{ rule }}
DOMAIN-SUFFIX,blizzard.com,{{ rule }}

// Prior
DOMAIN,client.amplifi.com,{{ rule }}
DOMAIN,ip.bjango.com,{{ rule }} // iStat Menu IP Test
DOMAIN-SUFFIX,alphassl.com,{{ rule }}
DOMAIN-SUFFIX,edu.cn,{{ rule }}

// Steam
DOMAIN-SUFFIX,steamcontent.com,{{ rule }}

// TeamViewer
IP-CIDR,139.220.243.27/32,{{ rule }},no-resolve
IP-CIDR,172.16.102.56/32,{{ rule }},no-resolve
IP-CIDR,185.188.32.1/28,{{ rule }},no-resolve
IP-CIDR,221.226.128.146/32,{{ rule }},no-resolve



# Domestic

DOMAIN-SUFFIX,cn,{{ rule }}

DOMAIN-SUFFIX,12306.com,{{ rule }}
DOMAIN-SUFFIX,126.net,{{ rule }}
DOMAIN-SUFFIX,163.com,{{ rule }}
DOMAIN-SUFFIX,360.cn,{{ rule }}
DOMAIN-SUFFIX,360.com,{{ rule }}
DOMAIN-SUFFIX,360buy.com,{{ rule }}
DOMAIN-SUFFIX,360buyimg.com,{{ rule }}
DOMAIN-SUFFIX,36kr.com,{{ rule }}
DOMAIN-SUFFIX,51ym.me,{{ rule }}
DOMAIN-SUFFIX,58.com,{{ rule }}
DOMAIN-SUFFIX,8686c.com,{{ rule }}
DOMAIN-SUFFIX,abercrombie.com,{{ rule }}
DOMAIN-SUFFIX,acfun.tv,{{ rule }}
DOMAIN-SUFFIX,acgvideo.com,{{ rule }}
DOMAIN-SUFFIX,adobesc.com,{{ rule }}
DOMAIN-SUFFIX,air-matters.com,{{ rule }}
DOMAIN-SUFFIX,air-matters.io,{{ rule }}
DOMAIN-SUFFIX,airtable.com,{{ rule }}
DOMAIN-SUFFIX,aixifan.com,{{ rule }}
DOMAIN-SUFFIX,akadns.net,{{ rule }}
DOMAIN-SUFFIX,alicdn.com,{{ rule }}
DOMAIN-SUFFIX,alipay.com,{{ rule }}
DOMAIN-SUFFIX,alipayobjects.com,{{ rule }}
DOMAIN-SUFFIX,aliyun.com,{{ rule }}
DOMAIN-SUFFIX,amap.com,{{ rule }}
DOMAIN-SUFFIX,apache.org,{{ rule }}
DOMAIN-SUFFIX,api.crisp.chat,{{ rule }}
DOMAIN-SUFFIX,api.termius.com,{{ rule }}
DOMAIN-SUFFIX,appshike.com,{{ rule }}
DOMAIN-SUFFIX,appstore.com,{{ rule }}
DOMAIN-SUFFIX,autonavi.com,{{ rule }}
DOMAIN-SUFFIX,aweme.snssdk.com,{{ rule }}
DOMAIN-SUFFIX,bababian.com,{{ rule }}
DOMAIN-SUFFIX,baidu.com,{{ rule }}
DOMAIN-SUFFIX,battle.net,{{ rule }}
DOMAIN-SUFFIX,bdimg.com,{{ rule }}
DOMAIN-SUFFIX,bdstatic.com,{{ rule }}
DOMAIN-SUFFIX,beatsbydre.com,{{ rule }}
DOMAIN-SUFFIX,bet365.com,{{ rule }}
DOMAIN-SUFFIX,bilibili.cn,{{ rule }}
DOMAIN-SUFFIX,bilibili.com,{{ rule }}
DOMAIN-SUFFIX,caiyunapp.com,{{ rule }}
DOMAIN-SUFFIX,ccgslb.com,{{ rule }}
DOMAIN-SUFFIX,ccgslb.net,{{ rule }}
DOMAIN-SUFFIX,chinacache.net,{{ rule }}
DOMAIN-SUFFIX,chunbo.com,{{ rule }}
DOMAIN-SUFFIX,chunboimg.com,{{ rule }}
DOMAIN-SUFFIX,clashroyaleapp.com,{{ rule }}
DOMAIN-SUFFIX,clouddn.com,{{ rule }}
DOMAIN-SUFFIX,cloudsigma.com,{{ rule }}
DOMAIN-SUFFIX,cloudxns.net,{{ rule }}
DOMAIN-SUFFIX,cmfu.com,{{ rule }}
DOMAIN-SUFFIX,cnbeta.com,{{ rule }}
DOMAIN-SUFFIX,cnbetacdn.com,{{ rule }}
DOMAIN-SUFFIX,culturedcode.com,{{ rule }}
DOMAIN-SUFFIX,dct-cloud.com,{{ rule }}
DOMAIN-SUFFIX,didialift.com,{{ rule }}
DOMAIN-SUFFIX,digicert.com,{{ rule }}
DOMAIN-SUFFIX,douban.com,{{ rule }}
DOMAIN-SUFFIX,doubanio.com,{{ rule }}
DOMAIN-SUFFIX,douyu.com,{{ rule }}
DOMAIN-SUFFIX,douyu.tv,{{ rule }}
DOMAIN-SUFFIX,douyutv.com,{{ rule }}
DOMAIN-SUFFIX,duokan.com,{{ rule }}
DOMAIN-SUFFIX,duoshuo.com,{{ rule }}
DOMAIN-SUFFIX,dytt8.net,{{ rule }}
DOMAIN-SUFFIX,easou.com,{{ rule }}
DOMAIN-SUFFIX,ecitic.com,{{ rule }}
DOMAIN-SUFFIX,ecitic.net,{{ rule }}
DOMAIN-SUFFIX,eclipse.org,{{ rule }}
DOMAIN-SUFFIX,eudic.net,{{ rule }}
DOMAIN-SUFFIX,ewqcxz.com,{{ rule }}
DOMAIN-SUFFIX,feng.com,{{ rule }}
DOMAIN-SUFFIX,fir.im,{{ rule }}
DOMAIN-SUFFIX,frdic.com,{{ rule }}
DOMAIN-SUFFIX,fresh-ideas.cc,{{ rule }}
DOMAIN-SUFFIX,geetest.com,{{ rule }}
DOMAIN-SUFFIX,godic.net,{{ rule }}
DOMAIN-SUFFIX,goodread.com,{{ rule }}
DOMAIN-SUFFIX,google.cn,{{ rule }}
DOMAIN-SUFFIX,gtimg.com,{{ rule }}
DOMAIN-SUFFIX,haibian.com,{{ rule }}
DOMAIN-SUFFIX,hao123.com,{{ rule }}
DOMAIN-SUFFIX,haosou.com,{{ rule }}
DOMAIN-SUFFIX,hdslb.com,{{ rule }}
DOMAIN-SUFFIX,hdslb.net,{{ rule }}
DOMAIN-SUFFIX,hollisterco.com,{{ rule }}
DOMAIN-SUFFIX,hongxiu.com,{{ rule }}
DOMAIN-SUFFIX,hxcdn.net,{{ rule }}
DOMAIN-SUFFIX,iciba.com,{{ rule }}
DOMAIN-SUFFIX,ifeng.com,{{ rule }}
DOMAIN-SUFFIX,ifengimg.com,{{ rule }}
DOMAIN-SUFFIX,images.unsplash.com,{{ rule }}
DOMAIN-SUFFIX,images-amazon.com,{{ rule }}
DOMAIN-SUFFIX,img4me.com,{{ rule }}
DOMAIN-SUFFIX,ipify.org,{{ rule }}
DOMAIN-SUFFIX,ipip.net,{{ rule }}
DOMAIN-SUFFIX,iqiyi.com,{{ rule }}
DOMAIN-SUFFIX,ithome.com,{{ rule }}
DOMAIN-SUFFIX,ixdzs.com,{{ rule }}
DOMAIN-SUFFIX,jd.com,{{ rule }}
DOMAIN-SUFFIX,jd.hk,{{ rule }}
DOMAIN-SUFFIX,jianshu.com,{{ rule }}
DOMAIN-SUFFIX,jianshu.io,{{ rule }}
DOMAIN-SUFFIX,jianshuapi.com,{{ rule }}
DOMAIN-SUFFIX,jiathis.com,{{ rule }}
DOMAIN-SUFFIX,jomodns.com,{{ rule }}
DOMAIN-SUFFIX,jsboxbbs.com,{{ rule }}
DOMAIN-SUFFIX,knewone.com,{{ rule }}
DOMAIN-SUFFIX,kuaidi100.com,{{ rule }}
DOMAIN-SUFFIX,lecloud.com,{{ rule }}
DOMAIN-SUFFIX,lemicp.com,{{ rule }}
DOMAIN-SUFFIX,letv.com,{{ rule }}
DOMAIN-SUFFIX,letvcloud.com,{{ rule }}
DOMAIN-SUFFIX,lizhi.io,{{ rule }}
DOMAIN-SUFFIX,localizecdn.com,{{ rule }}
DOMAIN-SUFFIX,lucifr.com,{{ rule }}
DOMAIN-SUFFIX,luoo.net,{{ rule }}
DOMAIN-SUFFIX,lxdns.com,{{ rule }}
DOMAIN-SUFFIX,mai.tn,{{ rule }}
DOMAIN-SUFFIX,maven.org,{{ rule }}
DOMAIN-SUFFIX,meizu.com,{{ rule }}
DOMAIN-SUFFIX,mi.com,{{ rule }}
DOMAIN-SUFFIX,miaopai.com,{{ rule }}
DOMAIN-SUFFIX,miui.com,{{ rule }}
DOMAIN-SUFFIX,miwifi.com,{{ rule }}
DOMAIN-SUFFIX,mob.com,{{ rule }}
DOMAIN-SUFFIX,moji.com,{{ rule }}
DOMAIN-SUFFIX,moke.com,{{ rule }}
DOMAIN-SUFFIX,mtalk.google.com,{{ rule }}
DOMAIN-SUFFIX,mxhichina.com,{{ rule }}
DOMAIN-SUFFIX,myqcloud.com,{{ rule }}
DOMAIN-SUFFIX,myunlu.com,{{ rule }}
DOMAIN-SUFFIX,netease.com,{{ rule }}
DOMAIN-SUFFIX,nfoservers.com,{{ rule }}
DOMAIN-SUFFIX,nssurge.com,{{ rule }}
DOMAIN-SUFFIX,nuomi.com,{{ rule }}
DOMAIN-SUFFIX,ourdvs.com,{{ rule }}
DOMAIN-SUFFIX,overcast.fm,{{ rule }}
DOMAIN-SUFFIX,paypal.com,{{ rule }}
DOMAIN-SUFFIX,paypalobjects.com,{{ rule }}
DOMAIN-SUFFIX,pgyer.com,{{ rule }}
DOMAIN-SUFFIX,pstatp.com,{{ rule }}
DOMAIN-SUFFIX,qbox.me,{{ rule }}
DOMAIN-SUFFIX,qcloud.com,{{ rule }}
DOMAIN-SUFFIX,qdaily.com,{{ rule }}
DOMAIN-SUFFIX,qdmm.com,{{ rule }}
DOMAIN-SUFFIX,qhimg.com,{{ rule }}
DOMAIN-SUFFIX,qidian.com,{{ rule }}
DOMAIN-SUFFIX,qihucdn.com,{{ rule }}
DOMAIN-SUFFIX,qin.io,{{ rule }}
DOMAIN-SUFFIX,qingmang.me,{{ rule }}
DOMAIN-SUFFIX,qingmang.mobi,{{ rule }}
DOMAIN-SUFFIX,qiniucdn.com,{{ rule }}
DOMAIN-SUFFIX,qiniudn.com,{{ rule }}
DOMAIN-SUFFIX,qiyi.com,{{ rule }}
DOMAIN-SUFFIX,qiyipic.com,{{ rule }}
DOMAIN-SUFFIX,qq.com,{{ rule }}
DOMAIN-SUFFIX,qqurl.com,{{ rule }}
DOMAIN-SUFFIX,rarbg.to,{{ rule }}
DOMAIN-SUFFIX,rrmj.tv,{{ rule }}
DOMAIN-SUFFIX,ruguoapp.com,{{ rule }}
DOMAIN-SUFFIX,sandai.net,{{ rule }}
DOMAIN-SUFFIX,sf-express.com,{{ rule }}
DOMAIN-SUFFIX,sinaapp.com,{{ rule }}
DOMAIN-SUFFIX,sinaimg.cn,{{ rule }}
DOMAIN-SUFFIX,sinaimg.com,{{ rule }}
DOMAIN-SUFFIX,sm.ms,{{ rule }}
DOMAIN-SUFFIX,smzdm.com,{{ rule }}
DOMAIN-SUFFIX,snssdk.com,{{ rule }}
DOMAIN-SUFFIX,snwx.com,{{ rule }}
DOMAIN-SUFFIX,so.com,{{ rule }}
DOMAIN-SUFFIX,sogou.com,{{ rule }}
DOMAIN-SUFFIX,sogoucdn.com,{{ rule }}
DOMAIN-SUFFIX,sohu.com,{{ rule }}
DOMAIN-SUFFIX,soku.com,{{ rule }}
DOMAIN-SUFFIX,soso.com,{{ rule }}
DOMAIN-SUFFIX,speedtest.net,{{ rule }}
DOMAIN-SUFFIX,sspai.com,{{ rule }}
DOMAIN-SUFFIX,startssl.com,{{ rule }}
DOMAIN-SUFFIX,store.steampowered.com,{{ rule }}
DOMAIN-SUFFIX,suning.com,{{ rule }}
DOMAIN-SUFFIX,symcd.com,{{ rule }}
DOMAIN-SUFFIX,taobao.com,{{ rule }}
DOMAIN-SUFFIX,teamviewer.com,{{ rule }}
DOMAIN-SUFFIX,tenpay.com,{{ rule }}
DOMAIN-SUFFIX,tietuku.com,{{ rule }}
DOMAIN-SUFFIX,tmall.com,{{ rule }}
DOMAIN-SUFFIX,tmzvps.com,{{ rule }}
DOMAIN-SUFFIX,trello.com,{{ rule }}
DOMAIN-SUFFIX,trellocdn.com,{{ rule }}
DOMAIN-SUFFIX,ttmeiju.com,{{ rule }}
DOMAIN-SUFFIX,tudou.com,{{ rule }}
DOMAIN-SUFFIX,udache.com,{{ rule }}
DOMAIN-SUFFIX,umengcloud.com,{{ rule }}
DOMAIN-SUFFIX,upaiyun.com,{{ rule }}
DOMAIN-SUFFIX,upyun.com,{{ rule }}
DOMAIN-SUFFIX,uxengine.net,{{ rule }}
DOMAIN-SUFFIX,v2ex.co,{{ rule }}
DOMAIN-SUFFIX,v2ex.com,{{ rule }}
DOMAIN-SUFFIX,wandoujia.com,{{ rule }}
DOMAIN-SUFFIX,weather.bjango.com,{{ rule }}
DOMAIN-SUFFIX,weather.com,{{ rule }}
DOMAIN-SUFFIX,webqxs.com,{{ rule }}
DOMAIN-SUFFIX,weibo.cn,{{ rule }}
DOMAIN-SUFFIX,weibo.com,{{ rule }}
DOMAIN-SUFFIX,weico.cc,{{ rule }}
DOMAIN-SUFFIX,weiphone.com,{{ rule }}
DOMAIN-SUFFIX,weiphone.net,{{ rule }}
DOMAIN-SUFFIX,wenku8.net,{{ rule }}
DOMAIN-SUFFIX,werewolf.53site.com,{{ rule }}
DOMAIN-SUFFIX,windowsupdate.com,{{ rule }}
DOMAIN-SUFFIX,wkcdn.com,{{ rule }}
DOMAIN-SUFFIX,workflowy.com,{{ rule }}
DOMAIN-SUFFIX,xdrig.com,{{ rule }}
DOMAIN-SUFFIX,xiami.com,{{ rule }}
DOMAIN-SUFFIX,xiami.net,{{ rule }}
DOMAIN-SUFFIX,xiaojukeji.com,{{ rule }}
DOMAIN-SUFFIX,xiaomi.com,{{ rule }}
DOMAIN-SUFFIX,xiaomi.net,{{ rule }}
DOMAIN-SUFFIX,xiaomicp.com,{{ rule }}
DOMAIN-SUFFIX,ximalaya.com,{{ rule }}
DOMAIN-SUFFIX,xitek.com,{{ rule }}
DOMAIN-SUFFIX,xmcdn.com,{{ rule }}
DOMAIN-SUFFIX,xslb.net,{{ rule }}
DOMAIN-SUFFIX,xteko.com,{{ rule }}
DOMAIN-SUFFIX,xunlei.com,{{ rule }}
DOMAIN-SUFFIX,yach.me,{{ rule }}
DOMAIN-SUFFIX,yeepay.com,{{ rule }}
DOMAIN-SUFFIX,yhd.com,{{ rule }}
DOMAIN-SUFFIX,yinxiang.com,{{ rule }}
DOMAIN-SUFFIX,yixia.com,{{ rule }}
DOMAIN-SUFFIX,ykimg.com,{{ rule }}
DOMAIN-SUFFIX,youdao.com,{{ rule }}
DOMAIN-SUFFIX,youku.com,{{ rule }}
DOMAIN-SUFFIX,yunjiasu-cdn.net,{{ rule }}
DOMAIN-SUFFIX,zealer.com,{{ rule }}
DOMAIN-SUFFIX,zgslb.net,{{ rule }}
DOMAIN-SUFFIX,zhihu.com,{{ rule }}
DOMAIN-SUFFIX,zhimg.com,{{ rule }}
DOMAIN-SUFFIX,zimuzu.tv,{{ rule }}
DOMAIN-SUFFIX,zmz002.com,{{ rule }}
{% endmacro %}
