{% macro main(rule) %}
# PROXY

// Client
PROCESS-NAME,Backup and Sync,{{ rule }}
PROCESS-NAME,Day One,{{ rule }}
PROCESS-NAME,Dropbox,{{ rule }}
PROCESS-NAME,LINE,{{ rule }}
PROCESS-NAME,node-webkit,{{ rule }}
# PROCESS-NAME,Resilio Sync,{{ rule }}
PROCESS-NAME,Spotify,{{ rule }}
PROCESS-NAME,Tweetbot,{{ rule }}
PROCESS-NAME,Twitter,{{ rule }}
PROCESS-NAME,Twitterrific,{{ rule }}
PROCESS-NAME,viu,{{ rule }}

// UA
USER-AGENT,%E7%BA%BD%E7%BA%A6%E6%97%B6%E6%8A%A5*,{{ rule }}
USER-AGENT,AwemeI18n*,{{ rule }}
USER-AGENT,Coinbase*,{{ rule }}
USER-AGENT,Instagram*,{{ rule }}
# USER-AGENT,Resilio Sync*,{{ rule }}
USER-AGENT,SoundCloud*,{{ rule }}
USER-AGENT,viu*,{{ rule }}
USER-AGENT,WeMusic*,{{ rule }}

// BBC
USER-AGENT,BBCiPlayer*,{{ rule }}
DOMAIN-KEYWORD,co.uk,{{ rule }}
DOMAIN-KEYWORD,uk-live,{{ rule }}
DOMAIN-SUFFIX,bbc.co,{{ rule }}
DOMAIN-SUFFIX,bbc.com,{{ rule }}

// CHOCO TV
USER-AGENT,TwDramas,{{ rule }}
DOMAIN-SUFFIX,chocotv.com.tw,{{ rule }}

// Epicgames
DOMAIN-KEYWORD,epicgames,{{ rule }}
DOMAIN-SUFFIX,helpshift.com,{{ rule }}

// Hulu
DOMAIN-SUFFIX,hulu.com,{{ rule }}

// Line
DOMAIN-SUFFIX,lin.ee,{{ rule }}
DOMAIN-SUFFIX,line.me,{{ rule }}
DOMAIN-SUFFIX,line.naver.jp,{{ rule }}
DOMAIN-SUFFIX,line-apps.com,{{ rule }}
DOMAIN-SUFFIX,line-cdn.net,{{ rule }}
DOMAIN-SUFFIX,line-scdn.net,{{ rule }}
DOMAIN-SUFFIX,nhncorp.jp,{{ rule }}

// MytvSUPER
DOMAIN-KEYWORD,nowtv100,{{ rule }}
DOMAIN-KEYWORD,rthklive,{{ rule }}
DOMAIN-SUFFIX,mytvsuper.com,{{ rule }}
DOMAIN-SUFFIX,tvb.com,{{ rule }}

// Microsoft
USER-AGENT,OneDrive*,{{ rule }}

DOMAIN-KEYWORD,microsoft,{{ rule }}
DOMAIN-SUFFIX,hotmail.com,{{ rule }}
DOMAIN-SUFFIX,live.com,{{ rule }}
DOMAIN-SUFFIX,live.net,{{ rule }}
DOMAIN-SUFFIX,msn.com,{{ rule }}
DOMAIN-SUFFIX,office.com,{{ rule }}
DOMAIN-SUFFIX,office.net,{{ rule }}
DOMAIN-SUFFIX,outlook.com,{{ rule }}

// Netflix
DOMAIN-SUFFIX,netflix.com,{{ rule }}
DOMAIN-SUFFIX,netflix.net,{{ rule }}
DOMAIN-SUFFIX,nflxext.com,{{ rule }}
DOMAIN-SUFFIX,nflximg.com,{{ rule }}
DOMAIN-SUFFIX,nflximg.net,{{ rule }}
DOMAIN-SUFFIX,nflxvideo.net,{{ rule }}

// Spark
DOMAIN-SUFFIX,api.amplitude.com,{{ rule }}
DOMAIN-SUFFIX,app.smartmailcloud.com,{{ rule }}
DOMAIN-SUFFIX,gate.hockeyapp.net,{{ rule }}
DOMAIN-SUFFIX,smartmailcloud.com,{{ rule }}

// Steam
DOMAIN-SUFFIX,fanatical.com,{{ rule }}
DOMAIN-SUFFIX,humblebundle.com,{{ rule }}
DOMAIN-SUFFIX,steamcommunity.com,{{ rule }}
DOMAIN-SUFFIX,steampowered.com,{{ rule }}
DOMAIN-SUFFIX,steamstatic.com,{{ rule }}

// WeMusic
DOMAIN-KEYWORD,joox,{{ rule }}

// Top blocked sites
DOMAIN-SUFFIX,2o7.net,{{ rule }}
DOMAIN-SUFFIX,4everProxy.com,{{ rule }}
DOMAIN-SUFFIX,4shared.com,{{ rule }}
DOMAIN-SUFFIX,4sqi.net,{{ rule }}
DOMAIN-SUFFIX,9to5mac.com,{{ rule }}
DOMAIN-SUFFIX,abpchina.org,{{ rule }}
DOMAIN-SUFFIX,accountkit.com,{{ rule }}
DOMAIN-SUFFIX,adblockplus.org,{{ rule }}
DOMAIN-SUFFIX,adobe.com,{{ rule }}
DOMAIN-SUFFIX,adobedtm.com,{{ rule }}
DOMAIN-SUFFIX,aerisapi.com,{{ rule }}
DOMAIN-SUFFIX,akamaihd.net,{{ rule }}
DOMAIN-SUFFIX,alibaba.com,{{ rule }}
DOMAIN-SUFFIX,alibabacloud.com,{{ rule }}
DOMAIN-SUFFIX,alfredapp.com,{{ rule }}
DOMAIN-SUFFIX,allconnected.co,{{ rule }}
DOMAIN-SUFFIX,amazon.com,{{ rule }}
DOMAIN-SUFFIX,amazonaws.com,{{ rule }}
DOMAIN-SUFFIX,ampproject.com,{{ rule }}
DOMAIN-SUFFIX,ampproject.net,{{ rule }}
DOMAIN-SUFFIX,ampproject.org,{{ rule }}
DOMAIN-SUFFIX,ancsconf.org,{{ rule }}
DOMAIN-SUFFIX,android.com,{{ rule }}
DOMAIN-SUFFIX,androidify.com,{{ rule }}
DOMAIN-SUFFIX,android-x86.org,{{ rule }}
DOMAIN-SUFFIX,angularjs.org,{{ rule }}
DOMAIN-SUFFIX,anthonycalzadilla.com,{{ rule }}
DOMAIN-SUFFIX,aol.com,{{ rule }}
DOMAIN-SUFFIX,aolcdn.com,{{ rule }}
DOMAIN-SUFFIX,api.mixpanel.com,{{ rule }}
DOMAIN-SUFFIX,api.tiktokv.com,{{ rule }}
DOMAIN-SUFFIX,api.urbandictionary.com,{{ rule }}
DOMAIN-SUFFIX,apigee.com,{{ rule }}
DOMAIN-SUFFIX,apk-dl.com,{{ rule }}
DOMAIN-SUFFIX,apkpure.com,{{ rule }}
DOMAIN-SUFFIX,appdownloader.net,{{ rule }}
DOMAIN-SUFFIX,apple-dns.net,{{ rule }}
DOMAIN-SUFFIX,app-measurement.com,{{ rule }}
DOMAIN-SUFFIX,appshopper.com,{{ rule }}
DOMAIN-SUFFIX,arcgis.com,{{ rule }}
DOMAIN-SUFFIX,archive.is,{{ rule }}
DOMAIN-SUFFIX,archive.org,{{ rule }}
DOMAIN-SUFFIX,archives.gov,{{ rule }}
DOMAIN-SUFFIX,armorgames.com,{{ rule }}
DOMAIN-SUFFIX,aspnetcdn.com,{{ rule }}
DOMAIN-SUFFIX,async.be,{{ rule }}
DOMAIN-SUFFIX,att.com,{{ rule }}
DOMAIN-SUFFIX,avgle.com,{{ rule }}
DOMAIN-SUFFIX,awsstatic.com,{{ rule }}
DOMAIN-SUFFIX,azureedge.net,{{ rule }}
DOMAIN-SUFFIX,azurewebsites.net,{{ rule }}
DOMAIN-SUFFIX,badoo.com,{{ rule }}
DOMAIN-SUFFIX,bandisoft.com,{{ rule }}
DOMAIN-SUFFIX,bbtoystore.com,{{ rule }}
DOMAIN-SUFFIX,betvictor.com,{{ rule }}
DOMAIN-SUFFIX,bigsound.org,{{ rule }}
DOMAIN-SUFFIX,bing.com,{{ rule }}
DOMAIN-SUFFIX,bing.net,{{ rule }}
DOMAIN-SUFFIX,bintray.com,{{ rule }}
DOMAIN-SUFFIX,bit.com,{{ rule }}
DOMAIN-SUFFIX,bit.do,{{ rule }}
DOMAIN-SUFFIX,bit.ly,{{ rule }}
DOMAIN-SUFFIX,bitbucket.org,{{ rule }}
DOMAIN-SUFFIX,bitcointalk.org,{{ rule }}
DOMAIN-SUFFIX,bitshare.com,{{ rule }}
DOMAIN-SUFFIX,bkrtx.com,{{ rule }}
DOMAIN-SUFFIX,blizzard.com,{{ rule }}
DOMAIN-SUFFIX,blog.com,{{ rule }}
DOMAIN-SUFFIX,blogcdn.com,{{ rule }}
DOMAIN-SUFFIX,blogger.com,{{ rule }}
DOMAIN-SUFFIX,bloglovin.com,{{ rule }}
DOMAIN-SUFFIX,blogsmithmedia.com,{{ rule }}
DOMAIN-SUFFIX,blogspot.hk,{{ rule }}
DOMAIN-SUFFIX,bloomberg.cn,{{ rule }}
DOMAIN-SUFFIX,bloomberg.com,{{ rule }}
DOMAIN-SUFFIX,books.com.tw,{{ rule }}
DOMAIN-SUFFIX,boomtrain.com,{{ rule }}
DOMAIN-SUFFIX,box.com,{{ rule }}
DOMAIN-SUFFIX,box.net,{{ rule }}
DOMAIN-SUFFIX,boxun.com,{{ rule }}
DOMAIN-SUFFIX,cachefly.net,{{ rule }}
DOMAIN-SUFFIX,cbc.ca,{{ rule }}
DOMAIN-SUFFIX,cdn.segment.com,{{ rule }}
DOMAIN-SUFFIX,cdnst.net,{{ rule }}
DOMAIN-SUFFIX,celestrak.com,{{ rule }}
DOMAIN-SUFFIX,census.gov,{{ rule }}
DOMAIN-SUFFIX,certificate-transparency.org,{{ rule }}
DOMAIN-SUFFIX,chinatimes.com,{{ rule }}
DOMAIN-SUFFIX,chrome.com,{{ rule }}
DOMAIN-SUFFIX,chromecast.com,{{ rule }}
DOMAIN-SUFFIX,chromercise.com,{{ rule }}
DOMAIN-SUFFIX,chromestatus.com,{{ rule }}
DOMAIN-SUFFIX,chromium.org,{{ rule }}
DOMAIN-SUFFIX,cl.ly,{{ rule }}
DOMAIN-SUFFIX,cloudflare.com,{{ rule }}
DOMAIN-SUFFIX,cloudfront.net,{{ rule }}
DOMAIN-SUFFIX,cloudgarage.jp,{{ rule }}
DOMAIN-SUFFIX,cloudmagic.com,{{ rule }}
DOMAIN-SUFFIX,cmail19.com,{{ rule }}
DOMAIN-SUFFIX,cnet.com,{{ rule }}
DOMAIN-SUFFIX,cnn.com,{{ rule }}
DOMAIN-SUFFIX,cocoapods.org,{{ rule }}
DOMAIN-SUFFIX,comodoca.com,{{ rule }}
DOMAIN-SUFFIX,content.office.net,{{ rule }}
DOMAIN-SUFFIX,culturedcode.com ,{{ rule }}
DOMAIN-SUFFIX,cygames.jp ,{{ rule }}
DOMAIN-SUFFIX,d.pr,{{ rule }}
DOMAIN-SUFFIX,danilo.to,{{ rule }}
DOMAIN-SUFFIX,daolan.net,{{ rule }}
DOMAIN-SUFFIX,data-vocabulary.org,{{ rule }}
DOMAIN-SUFFIX,dayone.me,{{ rule }}
DOMAIN-SUFFIX,db.tt,{{ rule }}
DOMAIN-SUFFIX,dcmilitary.com,{{ rule }}
DOMAIN-SUFFIX,deja.com,{{ rule }}
DOMAIN-SUFFIX,demdex.net,{{ rule }}
DOMAIN-SUFFIX,deskconnect.com,{{ rule }}
DOMAIN-SUFFIX,digisfera.com,{{ rule }}
DOMAIN-SUFFIX,digitaltrends.com,{{ rule }}
DOMAIN-SUFFIX,disconnect.me,{{ rule }}
DOMAIN-SUFFIX,disq.us,{{ rule }}
DOMAIN-SUFFIX,disqus.com,{{ rule }}
DOMAIN-SUFFIX,disquscdn.com,{{ rule }}
DOMAIN-SUFFIX,dmm.co.jp,{{ rule }}
DOMAIN-SUFFIX,dnsimple.com,{{ rule }}
DOMAIN-SUFFIX,docker.com,{{ rule }}
DOMAIN-SUFFIX,doub.io,{{ rule }}
DOMAIN-SUFFIX,dribbble.com,{{ rule }}
DOMAIN-SUFFIX,droplr.com,{{ rule }}
DOMAIN-SUFFIX,duckduckgo.com,{{ rule }}
DOMAIN-SUFFIX,dueapp.com,{{ rule }}
DOMAIN-SUFFIX,dw.com,{{ rule }}
DOMAIN-SUFFIX,easybib.com,{{ rule }}
DOMAIN-SUFFIX,economist.com,{{ rule }}
DOMAIN-SUFFIX,edgecastcdn.net,{{ rule }}
DOMAIN-SUFFIX,edgekey.net,{{ rule }}
DOMAIN-SUFFIX,edgesuite.net,{{ rule }}
DOMAIN-SUFFIX,engadget.com,{{ rule }}
DOMAIN-SUFFIX,entrust.net,{{ rule }}
DOMAIN-SUFFIX,eurekavpt.com,{{ rule }}
DOMAIN-SUFFIX,evernote.com,{{ rule }}
DOMAIN-SUFFIX,extmatrix.com,{{ rule }}
DOMAIN-SUFFIX,eyny.com,{{ rule }}
DOMAIN-SUFFIX,fabric.io,{{ rule }}
DOMAIN-SUFFIX,fast.com,{{ rule }}
DOMAIN-SUFFIX,fastly.net,{{ rule }}
DOMAIN-SUFFIX,fastmail.com,{{ rule }}
DOMAIN-SUFFIX,fc2.com,{{ rule }}
DOMAIN-SUFFIX,feedburner.com,{{ rule }}
DOMAIN-SUFFIX,feedly.com,{{ rule }}
DOMAIN-SUFFIX,feedsportal.com,{{ rule }}
DOMAIN-SUFFIX,fiftythree.com,{{ rule }}
DOMAIN-SUFFIX,firebaseio.com,{{ rule }}
DOMAIN-SUFFIX,flexibits.com,{{ rule }}
DOMAIN-SUFFIX,flickr.com,{{ rule }}
DOMAIN-SUFFIX,flipboard.com,{{ rule }}
DOMAIN-SUFFIX,flipkart.com,{{ rule }}
DOMAIN-SUFFIX,flitto.com,{{ rule }}
DOMAIN-SUFFIX,flurry.com,{{ rule }}
DOMAIN-SUFFIX,freeopenProxy.com,{{ rule }}
DOMAIN-SUFFIX,fullstory.com,{{ rule }}
DOMAIN-SUFFIX,fzlm.net,{{ rule }}
DOMAIN-SUFFIX,g.co,{{ rule }}
DOMAIN-SUFFIX,gabia.net,{{ rule }}
DOMAIN-SUFFIX,garena.com,{{ rule }}
DOMAIN-SUFFIX,gameloft.com,{{ rule }}
DOMAIN-SUFFIX,geni.us,{{ rule }}
DOMAIN-SUFFIX,get.how,{{ rule }}
DOMAIN-SUFFIX,getcloudapp.com,{{ rule }}
DOMAIN-SUFFIX,getfoxyProxy.org,{{ rule }}
DOMAIN-SUFFIX,getlantern.org,{{ rule }}
DOMAIN-SUFFIX,getmdl.io,{{ rule }}
DOMAIN-SUFFIX,getpricetag.com,{{ rule }}
DOMAIN-SUFFIX,gfw.press,{{ rule }}
DOMAIN-SUFFIX,gfx.ms,{{ rule }}
DOMAIN-SUFFIX,ggpht.com,{{ rule }}
DOMAIN-SUFFIX,ghostnoteapp.com,{{ rule }}
DOMAIN-SUFFIX,git.io,{{ rule }}
DOMAIN-SUFFIX,gitbook.com,{{ rule }}
DOMAIN-SUFFIX,globalsign.com,{{ rule }}
DOMAIN-SUFFIX,gmocloud.com,{{ rule }}
DOMAIN-SUFFIX,gmodules.com,{{ rule }}
DOMAIN-SUFFIX,go.com,{{ rule }}
DOMAIN-SUFFIX,go.jp,{{ rule }}
DOMAIN-SUFFIX,godaddy.com,{{ rule }}
DOMAIN-SUFFIX,golang.org,{{ rule }}
DOMAIN-SUFFIX,gongm.in,{{ rule }}
DOMAIN-SUFFIX,goo.gl,{{ rule }}
DOMAIN-SUFFIX,goodreaders.com,{{ rule }}
DOMAIN-SUFFIX,goodreads.com,{{ rule }}
DOMAIN-SUFFIX,gravatar.com,{{ rule }}
DOMAIN-SUFFIX,gstatic.cn,{{ rule }}
DOMAIN-SUFFIX,gstatic.com,{{ rule }}
DOMAIN-SUFFIX,gunsamerica.com,{{ rule }}
DOMAIN-SUFFIX,gvt0.com,{{ rule }}
DOMAIN-SUFFIX,gvt1.com,{{ rule }}
DOMAIN-SUFFIX,helpshift.com,{{ rule }}
DOMAIN-SUFFIX,hinet.net,{{ rule }}
DOMAIN-SUFFIX,hockeyapp.net,{{ rule }}
DOMAIN-SUFFIX,homedepot.com,{{ rule }}
DOMAIN-SUFFIX,hootsuite.com,{{ rule }}
DOMAIN-SUFFIX,howtoforge.com,{{ rule }}
DOMAIN-SUFFIX,iam.soy,{{ rule }}
DOMAIN-SUFFIX,icoco.com,{{ rule }}
DOMAIN-SUFFIX,icons8.com,{{ rule }}
DOMAIN-SUFFIX,ift.tt,{{ rule }}
DOMAIN-SUFFIX,ifttt.com,{{ rule }}
DOMAIN-SUFFIX,imageshack.us,{{ rule }}
DOMAIN-SUFFIX,img.ly,{{ rule }}
DOMAIN-SUFFIX,imgur.com,{{ rule }}
DOMAIN-SUFFIX,imore.com,{{ rule }}
DOMAIN-SUFFIX,ingress.com ,{{ rule }}
DOMAIN-SUFFIX,insder.co,{{ rule }}
DOMAIN-SUFFIX,instapaper.com,{{ rule }}
DOMAIN-SUFFIX,instructables.com,{{ rule }}
DOMAIN-SUFFIX,io.io,{{ rule }}
DOMAIN-SUFFIX,ip.sb,{{ rule }}
DOMAIN-SUFFIX,ipaddress.com,{{ rule }}
DOMAIN-SUFFIX,ipn.li,{{ rule }}
DOMAIN-SUFFIX,is.gd,{{ rule }}
DOMAIN-SUFFIX,ishowsapp.com,{{ rule }}
DOMAIN-SUFFIX,issuu.com,{{ rule }}
DOMAIN-SUFFIX,itgonglun.com,{{ rule }}
DOMAIN-SUFFIX,itun.es,{{ rule }}
DOMAIN-SUFFIX,ixquick.com,{{ rule }}
DOMAIN-SUFFIX,j.mp,{{ rule }}
DOMAIN-SUFFIX,javbus.com,{{ rule }}
DOMAIN-SUFFIX,js.revsci.net,{{ rule }}
DOMAIN-SUFFIX,jshint.com,{{ rule }}
DOMAIN-SUFFIX,jtvnw.net,{{ rule }}
DOMAIN-SUFFIX,justgetflux.com,{{ rule }}
DOMAIN-SUFFIX,kakao.co.kr,{{ rule }}
DOMAIN-SUFFIX,kakao.com,{{ rule }}
DOMAIN-SUFFIX,kakaocdn.net,{{ rule }}
DOMAIN-SUFFIX,kat.cr,{{ rule }}
DOMAIN-SUFFIX,kenengba.com,{{ rule }}
DOMAIN-SUFFIX,kik.com,{{ rule }}
DOMAIN-SUFFIX,klip.me,{{ rule }}
DOMAIN-SUFFIX,leancloud.com,{{ rule }}
DOMAIN-SUFFIX,leetcode.com,{{ rule }}
DOMAIN-SUFFIX,lhie1.com,{{ rule }}
DOMAIN-SUFFIX,libsyn.com,{{ rule }}
DOMAIN-SUFFIX,licdn.com,{{ rule }}
DOMAIN-SUFFIX,lightboxcdn.com,{{ rule }}
DOMAIN-SUFFIX,like.com,{{ rule }}
DOMAIN-SUFFIX,linkedin.com,{{ rule }}
DOMAIN-SUFFIX,linode.com,{{ rule }}
DOMAIN-SUFFIX,lithium.com,{{ rule }}
DOMAIN-SUFFIX,littlehj.com,{{ rule }}
DOMAIN-SUFFIX,livefilestore.com,{{ rule }}
DOMAIN-SUFFIX,llnwd.net,{{ rule }}
DOMAIN-SUFFIX,localnetwork.uop,{{ rule }}
DOMAIN-SUFFIX,logmein.com,{{ rule }}
DOMAIN-SUFFIX,macid.co,{{ rule }}
DOMAIN-SUFFIX,macromedia.com,{{ rule }}
DOMAIN-SUFFIX,macrumors.com,{{ rule }}
DOMAIN-SUFFIX,manhuaren.com,{{ rule }}
DOMAIN-SUFFIX,marketwatch.com,{{ rule }}
DOMAIN-SUFFIX,mashable.com,{{ rule }}
DOMAIN-SUFFIX,mathjax.org,{{ rule }}
DOMAIN-SUFFIX,medium.com,{{ rule }}
DOMAIN-SUFFIX,mega.co.nz,{{ rule }}
DOMAIN-SUFFIX,mega.nz,{{ rule }}
DOMAIN-SUFFIX,megaupload.com,{{ rule }}
DOMAIN-SUFFIX,microsofttranslator.com,{{ rule }}
DOMAIN-SUFFIX,mindnode.com,{{ rule }}
DOMAIN-SUFFIX,mlssoccer.com,{{ rule }}
DOMAIN-SUFFIX,mobile01.com,{{ rule }}
DOMAIN-SUFFIX,modmyi.com,{{ rule }}
DOMAIN-SUFFIX,moves-export.com,{{ rule }}
DOMAIN-SUFFIX,mp3buscador.com,{{ rule }}
DOMAIN-SUFFIX,msedge.net,{{ rule }}
DOMAIN-SUFFIX,mycnnews.com,{{ rule }}
DOMAIN-SUFFIX,myfontastic.com,{{ rule }}
DOMAIN-SUFFIX,name.com,{{ rule }}
DOMAIN-SUFFIX,nasa.gov,{{ rule }}
DOMAIN-SUFFIX,ndr.de,{{ rule }}
DOMAIN-SUFFIX,netdna-cdn.com,{{ rule }}
DOMAIN-SUFFIX,newipnow.com,{{ rule }}
DOMAIN-SUFFIX,nextmedia.com,{{ rule }}
DOMAIN-SUFFIX,nih.gov,{{ rule }}
DOMAIN-SUFFIX,nintendo.com,{{ rule }}
DOMAIN-SUFFIX,nintendo.net,{{ rule }}
DOMAIN-SUFFIX,notion.so,{{ rule }}
DOMAIN-SUFFIX,novafile.com,{{ rule }}
DOMAIN-SUFFIX,nrk.no,{{ rule }}
DOMAIN-SUFFIX,nsstatic.net,{{ rule }}
DOMAIN-SUFFIX,nssurge.com,{{ rule }}
DOMAIN-SUFFIX,nyt.com,{{ rule }}
DOMAIN-SUFFIX,nytimes.com,{{ rule }}
DOMAIN-SUFFIX,nytimg.com,{{ rule }}
DOMAIN-SUFFIX,nytstyle.com,{{ rule }}
DOMAIN-SUFFIX,office365.com,{{ rule }}
DOMAIN-SUFFIX,omnigroup.com,{{ rule }}
DOMAIN-SUFFIX,onedrive.com,{{ rule }}
DOMAIN-SUFFIX,onedrive.live.com,{{ rule }}
DOMAIN-SUFFIX,onenote.com,{{ rule }}
DOMAIN-SUFFIX,ooyala.com,{{ rule }}
DOMAIN-SUFFIX,openvpn.net,{{ rule }}
DOMAIN-SUFFIX,openwrt.org,{{ rule }}
DOMAIN-SUFFIX,optimizely.com,{{ rule }}
DOMAIN-SUFFIX,orkut.com,{{ rule }}
DOMAIN-SUFFIX,osha.gov,{{ rule }}
DOMAIN-SUFFIX,osxdaily.com,{{ rule }}
DOMAIN-SUFFIX,ow.ly,{{ rule }}
DOMAIN-SUFFIX,paddle.com,{{ rule }}
DOMAIN-SUFFIX,paddleapi.com,{{ rule }}
DOMAIN-SUFFIX,pandora.com,{{ rule }}
DOMAIN-SUFFIX,panoramio.com,{{ rule }}
DOMAIN-SUFFIX,parallels.com,{{ rule }}
DOMAIN-SUFFIX,parse.com,{{ rule }}
DOMAIN-SUFFIX,pdfexpert.com,{{ rule }}
DOMAIN-SUFFIX,periscope.tv,{{ rule }}
DOMAIN-SUFFIX,piaotian.net,{{ rule }}
DOMAIN-SUFFIX,picacomic.com,{{ rule }}
DOMAIN-SUFFIX,picasaweb.com,{{ rule }}
DOMAIN-SUFFIX,pinboard.in,{{ rule }}
DOMAIN-SUFFIX,ping.pe,{{ rule }}
DOMAIN-SUFFIX,pinterest.com,{{ rule }}
DOMAIN-SUFFIX,pixelmator.com,{{ rule }}
DOMAIN-SUFFIX,pixiv.net,{{ rule }}
DOMAIN-SUFFIX,pixnet.net,{{ rule }}
DOMAIN-SUFFIX,playpcesor.com,{{ rule }}
DOMAIN-SUFFIX,playstation.com,{{ rule }}
DOMAIN-SUFFIX,playstation.com.hk,{{ rule }}
DOMAIN-SUFFIX,playstation.net,{{ rule }}
DOMAIN-SUFFIX,playstationnetwork.com,{{ rule }}
DOMAIN-SUFFIX,pokemon.com,{{ rule }}
DOMAIN-SUFFIX,polymer-project.org,{{ rule }}
DOMAIN-SUFFIX,popo.tw,{{ rule }}
DOMAIN-SUFFIX,potato.im,{{ rule }}
DOMAIN-SUFFIX,prfct.co,{{ rule }}
DOMAIN-SUFFIX,proxfree.com,{{ rule }}
DOMAIN-SUFFIX,psiphon3.com,{{ rule }}
DOMAIN-SUFFIX,ptt.cc,{{ rule }}
DOMAIN-SUFFIX,pubu.com.tw,{{ rule }}
DOMAIN-SUFFIX,puffinbrowser.com,{{ rule }}
DOMAIN-SUFFIX,pushbullet.com,{{ rule }}
DOMAIN-SUFFIX,pushwoosh.com,{{ rule }}
DOMAIN-SUFFIX,pximg.net,{{ rule }}
DOMAIN-SUFFIX,quora.com,{{ rule }}
DOMAIN-SUFFIX,quoracdn.net,{{ rule }}
DOMAIN-SUFFIX,readingtimes.com.tw,{{ rule }}
DOMAIN-SUFFIX,readmoo.com,{{ rule }}
DOMAIN-SUFFIX,recaptcha.net,{{ rule }}
DOMAIN-SUFFIX,reddit.com,{{ rule }}
DOMAIN-SUFFIX,redditmedia.com,{{ rule }}
DOMAIN-SUFFIX,reuters.com,{{ rule }}
DOMAIN-SUFFIX,rfi.fr,{{ rule }}
DOMAIN-SUFFIX,rileyguide.com,{{ rule }}
DOMAIN-SUFFIX,rime.im,{{ rule }}
DOMAIN-SUFFIX,rsf.org,{{ rule }}
DOMAIN-SUFFIX,sciencedaily.com,{{ rule }}
DOMAIN-SUFFIX,sciencemag.org,{{ rule }}
DOMAIN-SUFFIX,scribd.com,{{ rule }}
DOMAIN-SUFFIX,search.com,{{ rule }}
DOMAIN-SUFFIX,servebom.com,{{ rule }}
DOMAIN-SUFFIX,sfx.ms,{{ rule }}
DOMAIN-SUFFIX,shadowsocks.org,{{ rule }}
DOMAIN-SUFFIX,shadowverse.jp,{{ rule }}
DOMAIN-SUFFIX,sharethis.com,{{ rule }}
DOMAIN-SUFFIX,shazam.com,{{ rule }}
DOMAIN-SUFFIX,shutterstock.com,{{ rule }}
DOMAIN-SUFFIX,sidelinesnews.com,{{ rule }}
DOMAIN-SUFFIX,simp.ly,{{ rule }}
DOMAIN-SUFFIX,simplenote.com,{{ rule }}
DOMAIN-SUFFIX,sketchappsources.com,{{ rule }}
DOMAIN-SUFFIX,skype.com,{{ rule }}
DOMAIN-SUFFIX,slack.com,{{ rule }}
DOMAIN-SUFFIX,slack-edge.com,{{ rule }}
DOMAIN-SUFFIX,slack-msgs.com,{{ rule }}
DOMAIN-SUFFIX,slideshare.net,{{ rule }}
DOMAIN-SUFFIX,smartdnsproxy.com,{{ rule }}
DOMAIN-SUFFIX,smh.com.au,{{ rule }}
DOMAIN-SUFFIX,snapchat.com,{{ rule }}
DOMAIN-SUFFIX,sndcdn.com,{{ rule }}
DOMAIN-SUFFIX,sockslist.net,{{ rule }}
DOMAIN-SUFFIX,sony.com,{{ rule }}
DOMAIN-SUFFIX,sony.com.hk,{{ rule }}
DOMAIN-SUFFIX,sonyentertainmentnetwork.com,{{ rule }}
DOMAIN-SUFFIX,soundcloud.com,{{ rule }}
DOMAIN-SUFFIX,sourceforge.net,{{ rule }}
DOMAIN-SUFFIX,sowers.org.hk,{{ rule }}
DOMAIN-SUFFIX,speedsmart.net,{{ rule }}
DOMAIN-SUFFIX,spike.com,{{ rule }}
DOMAIN-SUFFIX,squarespace.com,{{ rule }}
DOMAIN-SUFFIX,ssa.gov,{{ rule }}
DOMAIN-SUFFIX,sstatic.net,{{ rule }}
DOMAIN-SUFFIX,st.luluku.pw,{{ rule }}
DOMAIN-SUFFIX,stackoverflow.com,{{ rule }}
DOMAIN-SUFFIX,starp2p.com,{{ rule }}
DOMAIN-SUFFIX,startpage.com,{{ rule }}
DOMAIN-SUFFIX,state.gov,{{ rule }}
DOMAIN-SUFFIX,staticflickr.com,{{ rule }}
DOMAIN-SUFFIX,storify.com,{{ rule }}
DOMAIN-SUFFIX,stumbleupon.com,{{ rule }}
DOMAIN-SUFFIX,sugarsync.com,{{ rule }}
DOMAIN-SUFFIX,supermariorun.com,{{ rule }}
DOMAIN-SUFFIX,surfeasy.com.au,{{ rule }}
DOMAIN-SUFFIX,surge.run,{{ rule }}
DOMAIN-SUFFIX,surrenderat20.net,{{ rule }}
DOMAIN-SUFFIX,sydneytoday.com,{{ rule }}
DOMAIN-SUFFIX,symauth.com,{{ rule }}
DOMAIN-SUFFIX,symcb.com,{{ rule }}
DOMAIN-SUFFIX,symcd.com,{{ rule }}
DOMAIN-SUFFIX,t.me,{{ rule }}
DOMAIN-SUFFIX,t66y.com,{{ rule }}
DOMAIN-SUFFIX,tablesgenerator.com,{{ rule }}
DOMAIN-SUFFIX,tabtter.jp,{{ rule }}
DOMAIN-SUFFIX,talk853.com,{{ rule }}
DOMAIN-SUFFIX,talkboxapp.com,{{ rule }}
DOMAIN-SUFFIX,talkonly.net,{{ rule }}
DOMAIN-SUFFIX,tapbots.com,{{ rule }}
DOMAIN-SUFFIX,tapbots.net,{{ rule }}
DOMAIN-SUFFIX,tdesktop.com,{{ rule }}
DOMAIN-SUFFIX,techcrunch.com,{{ rule }}
DOMAIN-SUFFIX,technorati.com,{{ rule }}
DOMAIN-SUFFIX,techsmith.com,{{ rule }}
DOMAIN-SUFFIX,teddysun.com,{{ rule }}
DOMAIN-SUFFIX,telegra.ph,{{ rule }}
DOMAIN-SUFFIX,textnow.me,{{ rule }}
DOMAIN-SUFFIX,thebobs.com,{{ rule }}
DOMAIN-SUFFIX,theinitium.com,{{ rule }}
DOMAIN-SUFFIX,thepiratebay.org,{{ rule }}
DOMAIN-SUFFIX,theverge.com,{{ rule }}
DOMAIN-SUFFIX,thewgo.org,{{ rule }}
DOMAIN-SUFFIX,tiltbrush.com,{{ rule }}
DOMAIN-SUFFIX,time.com,{{ rule }}
DOMAIN-SUFFIX,timeinc.net,{{ rule }}
DOMAIN-SUFFIX,tinder.com,{{ rule }}
DOMAIN-SUFFIX,tiny.cc,{{ rule }}
DOMAIN-SUFFIX,tinychat.com,{{ rule }}
DOMAIN-SUFFIX,tinypic.com,{{ rule }}
DOMAIN-SUFFIX,tmblr.co,{{ rule }}
DOMAIN-SUFFIX,todoist.com,{{ rule }}
DOMAIN-SUFFIX,togetter.com,{{ rule }}
DOMAIN-SUFFIX,tokyocn.com,{{ rule }}
DOMAIN-SUFFIX,tomshardware.com,{{ rule }}
DOMAIN-SUFFIX,torcn.com,{{ rule }}
DOMAIN-SUFFIX,torrentprivacy.com,{{ rule }}
DOMAIN-SUFFIX,torrentproject.se,{{ rule }}
DOMAIN-SUFFIX,torrentz.eu,{{ rule }}
DOMAIN-SUFFIX,traffichaus.com,{{ rule }}
DOMAIN-SUFFIX,trakt.tv,{{ rule }}
DOMAIN-SUFFIX,transparency.org,{{ rule }}
DOMAIN-SUFFIX,trello.com,{{ rule }}
DOMAIN-SUFFIX,trendsmap.com,{{ rule }}
DOMAIN-SUFFIX,trulyergonomic.com,{{ rule }}
DOMAIN-SUFFIX,trustasiassl.com,{{ rule }}
DOMAIN-SUFFIX,tt-rss.org,{{ rule }}
DOMAIN-SUFFIX,ttvnw.net,{{ rule }}
DOMAIN-SUFFIX,tumblr.co,{{ rule }}
DOMAIN-SUFFIX,tumblr.com,{{ rule }}
DOMAIN-SUFFIX,turbobit.net,{{ rule }}
DOMAIN-SUFFIX,tv.com,{{ rule }}
DOMAIN-SUFFIX,tweetdeck.com,{{ rule }}
DOMAIN-SUFFIX,tweetmarker.net,{{ rule }}
DOMAIN-SUFFIX,twimg.co,{{ rule }}
DOMAIN-SUFFIX,twitch.tv,{{ rule }}
DOMAIN-SUFFIX,twitthat.com,{{ rule }}
DOMAIN-SUFFIX,twtkr.com,{{ rule }}
DOMAIN-SUFFIX,twttr.com,{{ rule }}
DOMAIN-SUFFIX,txmblr.com,{{ rule }}
DOMAIN-SUFFIX,typcn.com,{{ rule }}
DOMAIN-SUFFIX,typekit.net,{{ rule }}
DOMAIN-SUFFIX,typography.com,{{ rule }}
DOMAIN-SUFFIX,ubertags.com,{{ rule }}
DOMAIN-SUFFIX,ublock.org,{{ rule }}
DOMAIN-SUFFIX,ubnt.com,{{ rule }}
DOMAIN-SUFFIX,uchicago.edu,{{ rule }}
DOMAIN-SUFFIX,udn.com,{{ rule }}
DOMAIN-SUFFIX,ugo.com,{{ rule }}
DOMAIN-SUFFIX,uhdwallpapers.org,{{ rule }}
DOMAIN-SUFFIX,ulyssesapp.com,{{ rule }}
DOMAIN-SUFFIX,unblockdmm.com,{{ rule }}
DOMAIN-SUFFIX,unblocksites.co,{{ rule }}
DOMAIN-SUFFIX,unpo.org,{{ rule }}
DOMAIN-SUFFIX,unsplash.com,{{ rule }}
DOMAIN-SUFFIX,untraceable.us,{{ rule }}
DOMAIN-SUFFIX,uploaded.net,{{ rule }}
DOMAIN-SUFFIX,uProxy.org,{{ rule }}
DOMAIN-SUFFIX,upwork.com,{{ rule }}
DOMAIN-SUFFIX,urchin.com,{{ rule }}
DOMAIN-SUFFIX,urlparser.com,{{ rule }}
DOMAIN-SUFFIX,us.to,{{ rule }}
DOMAIN-SUFFIX,usertrust.com,{{ rule }}
DOMAIN-SUFFIX,usgs.gov,{{ rule }}
DOMAIN-SUFFIX,usma.edu,{{ rule }}
DOMAIN-SUFFIX,uspto.gov,{{ rule }}
DOMAIN-SUFFIX,ustream.tv,{{ rule }}
DOMAIN-SUFFIX,v.gd,{{ rule }}
DOMAIN-SUFFIX,v2ray.com,{{ rule }}
DOMAIN-SUFFIX,van001.com,{{ rule }}
DOMAIN-SUFFIX,vanpeople.com,{{ rule }}
DOMAIN-SUFFIX,vansky.com,{{ rule }}
DOMAIN-SUFFIX,vbstatic.co,{{ rule }}
DOMAIN-SUFFIX,venchina.com,{{ rule }}
DOMAIN-SUFFIX,venturebeat.com,{{ rule }}
DOMAIN-SUFFIX,veoh.com,{{ rule }}
DOMAIN-SUFFIX,verizonwireless.com,{{ rule }}
DOMAIN-SUFFIX,viber.com,{{ rule }}
DOMAIN-SUFFIX,vid.me,{{ rule }}
DOMAIN-SUFFIX,videomega.tv,{{ rule }}
DOMAIN-SUFFIX,vidinfo.org,{{ rule }}
DOMAIN-SUFFIX,vimeo.com,{{ rule }}
DOMAIN-SUFFIX,vimeocdn.com,{{ rule }}
DOMAIN-SUFFIX,vimperator.org,{{ rule }}
DOMAIN-SUFFIX,vine.co,{{ rule }}
DOMAIN-SUFFIX,visibletweets.com,{{ rule }}
DOMAIN-SUFFIX,viu.com,{{ rule }}
DOMAIN-SUFFIX,vivaldi.com,{{ rule }}
DOMAIN-SUFFIX,voachinese.com,{{ rule }}
DOMAIN-SUFFIX,vocativ.com,{{ rule }}
DOMAIN-SUFFIX,vox-cdn.com,{{ rule }}
DOMAIN-SUFFIX,vpnaccount.org,{{ rule }}
DOMAIN-SUFFIX,vpnbook.com,{{ rule }}
DOMAIN-SUFFIX,vpngate.net,{{ rule }}
DOMAIN-SUFFIX,vsco.co,{{ rule }}
DOMAIN-SUFFIX,vultr.com,{{ rule }}
DOMAIN-SUFFIX,vzw.com,{{ rule }}
DOMAIN-SUFFIX,w.org,{{ rule }}
DOMAIN-SUFFIX,w3schools.com,{{ rule }}
DOMAIN-SUFFIX,wattpad.com,{{ rule }}
DOMAIN-SUFFIX,web2project.net,{{ rule }}
DOMAIN-SUFFIX,webfreer.com,{{ rule }}
DOMAIN-SUFFIX,weblagu.com,{{ rule }}
DOMAIN-SUFFIX,websnapr.com,{{ rule }}
DOMAIN-SUFFIX,webtype.com,{{ rule }}
DOMAIN-SUFFIX,webwarper.net,{{ rule }}
DOMAIN-SUFFIX,wenxuecity.com,{{ rule }}
DOMAIN-SUFFIX,westca.com,{{ rule }}
DOMAIN-SUFFIX,westpoint.edu,{{ rule }}
DOMAIN-SUFFIX,whatbrowser.org,{{ rule }}
DOMAIN-SUFFIX,wikileaks.info,{{ rule }}
DOMAIN-SUFFIX,wikileaks.org,{{ rule }}
DOMAIN-SUFFIX,wikileaks-forum.com,{{ rule }}
DOMAIN-SUFFIX,wikimedia.org,{{ rule }}
DOMAIN-SUFFIX,wikipedia.com,{{ rule }}
DOMAIN-SUFFIX,wikipedia.org,{{ rule }}
DOMAIN-SUFFIX,windows.com,{{ rule }}
DOMAIN-SUFFIX,windows.net,{{ rule }}
DOMAIN-SUFFIX,wn.com,{{ rule }}
DOMAIN-SUFFIX,wordpress.com,{{ rule }}
DOMAIN-SUFFIX,workflow.is,{{ rule }}
DOMAIN-SUFFIX,worldcat.org,{{ rule }}
DOMAIN-SUFFIX,wow.com,{{ rule }}
DOMAIN-SUFFIX,wp.com,{{ rule }}
DOMAIN-SUFFIX,wsj.com,{{ rule }}
DOMAIN-SUFFIX,wsj.net,{{ rule }}
DOMAIN-SUFFIX,wwitv.com,{{ rule }}
DOMAIN-SUFFIX,xanga.com,{{ rule }}
DOMAIN-SUFFIX,xclient.info,{{ rule }}
DOMAIN-SUFFIX,xda-developers.com,{{ rule }}
DOMAIN-SUFFIX,xeeno.com,{{ rule }}
DOMAIN-SUFFIX,xiti.com,{{ rule }}
DOMAIN-SUFFIX,xuite.net,{{ rule }}
DOMAIN-SUFFIX,xvideos.com,{{ rule }}
DOMAIN-SUFFIX,yahoo.com,{{ rule }}
DOMAIN-SUFFIX,yahooapis.com,{{ rule }}
DOMAIN-SUFFIX,yasni.co.uk,{{ rule }}
DOMAIN-SUFFIX,yastatic.net,{{ rule }}
DOMAIN-SUFFIX,yeeyi.com,{{ rule }}
DOMAIN-SUFFIX,yesasia.com,{{ rule }}
DOMAIN-SUFFIX,yes-news.com,{{ rule }}
DOMAIN-SUFFIX,yidio.com,{{ rule }}
DOMAIN-SUFFIX,yimg.com,{{ rule }}
DOMAIN-SUFFIX,ying.com,{{ rule }}
DOMAIN-SUFFIX,yorkbbs.ca,{{ rule }}
DOMAIN-SUFFIX,youmaker.com,{{ rule }}
DOMAIN-SUFFIX,yourlisten.com,{{ rule }}
DOMAIN-SUFFIX,youtu.be,{{ rule }}
DOMAIN-SUFFIX,yoyo.org,{{ rule }}
DOMAIN-SUFFIX,ytimg.com,{{ rule }}
DOMAIN-SUFFIX,zacebook.com,{{ rule }}
DOMAIN-SUFFIX,zalmos.com,{{ rule }}
DOMAIN-SUFFIX,zaobao.com.sg,{{ rule }}
DOMAIN-SUFFIX,zeutch.com,{{ rule }}
DOMAIN-SUFFIX,zynamics.com,{{ rule }}

// Force some domains which are fucked by GFW while resolving DNS,or do not respect the system Proxy
DOMAIN-KEYWORD,appledaily,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,beetalk,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,blogspot,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,dropbox,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,facebook,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,github,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,porn,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,spotify,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,telegram,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,twitter,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,whatsapp,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,youtube,{{ rule }},force-remote-dns
DOMAIN-KEYWORD,google,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,1e100.net,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,2mdn.net,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,abc.xyz,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,akamai.net,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,appspot.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,autodraw.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,bandwagonhost.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,blogblog.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,cdninstagram.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,chromeexperiments.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,creativelab5.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,crittercism.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,culturalspot.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,dartlang.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,fb.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,fb.me,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,fbcdn.net,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,fbsbx.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,gcr.io,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,gmail.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,gosetsuden.jp,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,gvt1.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,gwtproject.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,heroku.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,html5rocks.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,instagram.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,keyhole.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,kobo.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,kobobooks.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,madewithcode.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,material.io,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,messenger.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,netmarble.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,nianticlabs.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,pinimg.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,pubnub.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,scdn.co,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,t.co,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,tensorflow.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,toggleable.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,torproject.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,twimg.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,twitpic.com,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,unfiltered.news,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,waveprotocol.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,webmproject.org,{{ rule }},force-remote-dns
DOMAIN-SUFFIX,webrtc.org,{{ rule }},force-remote-dns

// Amazon
IP-CIDR,13.32.0.0/16,{{ rule }},no-resolve
IP-CIDR,13.33.0.0/16,{{ rule }},no-resolve
IP-CIDR,13.35.0.0/17,{{ rule }},no-resolve
IP-CIDR,18.184.0.0/15,{{ rule }},no-resolve
IP-CIDR,18.194.0.0/15,{{ rule }},no-resolve
IP-CIDR,18.208.0.0/13,{{ rule }},no-resolve
IP-CIDR,18.232.0.0/14,{{ rule }},no-resolve
IP-CIDR,52.200.0.0/13,{{ rule }},no-resolve
IP-CIDR,52.58.0.0/15,{{ rule }},no-resolve
IP-CIDR,52.74.0.0/16,{{ rule }},no-resolve
IP-CIDR,52.77.0.0/16,{{ rule }},no-resolve
IP-CIDR,52.84.0.0/15,{{ rule }},no-resolve
IP-CIDR,54.156.0.0/14,{{ rule }},no-resolve
IP-CIDR,54.226.0.0/15,{{ rule }},no-resolve
IP-CIDR,54.230.156.0/22,{{ rule }},no-resolve
IP-CIDR,54.93.0.0/16,{{ rule }},no-resolve

// Facebook
IP-CIDR,103.4.96.0/22,{{ rule }},no-resolve
IP-CIDR,129.134.0.0/17,{{ rule }},no-resolve
IP-CIDR,157.240.0.0/17,{{ rule }},no-resolve
IP-CIDR,173.252.64.0/19,{{ rule }},no-resolve
IP-CIDR,173.252.96.0/19,{{ rule }},no-resolve
IP-CIDR,179.60.192.0/22,{{ rule }},no-resolve
IP-CIDR,185.60.216.0/22,{{ rule }},no-resolve
IP-CIDR,204.15.20.0/22,{{ rule }},no-resolve
IP-CIDR,31.13.24.0/21,{{ rule }},no-resolve
IP-CIDR,31.13.64.0/18,{{ rule }},no-resolve
IP-CIDR,45.64.40.0/22,{{ rule }},no-resolve
IP-CIDR,66.220.144.0/20,{{ rule }},no-resolve
IP-CIDR,69.171.224.0/19,{{ rule }},no-resolve
IP-CIDR,69.63.176.0/20,{{ rule }},no-resolve
IP-CIDR,74.119.76.0/22,{{ rule }},no-resolve

// Google
IP-CIDR,173.194.0.0/16,{{ rule }},no-resolve
IP-CIDR,74.125.0.0/16,{{ rule }},no-resolve

// Kakao Talk
IP-CIDR,1.201.0.0/24,{{ rule }},no-resolve
IP-CIDR,103.246.56.0/22,{{ rule }},no-resolve
IP-CIDR,103.27.148.0/22,{{ rule }},no-resolve
IP-CIDR,110.76.140.0/22,{{ rule }},no-resolve
IP-CIDR,113.61.104.0/22,{{ rule }},no-resolve
IP-CIDR,27.0.236.0/22,{{ rule }},no-resolve

// LINE
IP-CIDR,103.2.28.0/22,{{ rule }},no-resolve
IP-CIDR,119.235.224.0/21,{{ rule }},no-resolve
IP-CIDR,119.235.232.0/23,{{ rule }},no-resolve
IP-CIDR,119.235.235.0/24,{{ rule }},no-resolve
IP-CIDR,119.235.236.0/23,{{ rule }},no-resolve
IP-CIDR,125.6.146.0/24,{{ rule }},no-resolve
IP-CIDR,125.6.149.0/24,{{ rule }},no-resolve
IP-CIDR,125.6.190.0/24,{{ rule }},no-resolve
IP-CIDR,125.209.208.0/20,{{ rule }},no-resolve
IP-CIDR,203.104.103.0/24,{{ rule }},no-resolve
IP-CIDR,203.104.128.0/20,{{ rule }},no-resolve
IP-CIDR,203.174.66.64/26,{{ rule }},no-resolve
IP-CIDR,203.174.77.0/24,{{ rule }},no-resolve

// Potato Chat
IP-CIDR,13.251.24.157/24,{{ rule }},no-resolve
IP-CIDR,13.251.41.203/24,{{ rule }},no-resolve
IP-CIDR,17.252.156.147/24,{{ rule }},no-resolve
IP-CIDR,17.252.157.26/24,{{ rule }},no-resolve

// SoftLayer
IP-CIDR,74.86.0.0/16,{{ rule }},no-resolve
IP-CIDR,75.126.0.0/16,{{ rule }},no-resolve
IP-CIDR,174.37.0.0/16,{{ rule }},no-resolve
IP-CIDR,208.43.0.0/16,{{ rule }},no-resolve

// Telegram
IP-CIDR,109.239.140.0/24,{{ rule }},no-resolve
IP-CIDR,149.154.160.0/20,{{ rule }},no-resolve
IP-CIDR,149.154.164.0/22,{{ rule }},no-resolve
IP-CIDR,149.154.168.0/22,{{ rule }},no-resolve
IP-CIDR,149.154.172.0/22,{{ rule }},no-resolve
IP-CIDR,91.108.4.0/22,{{ rule }},no-resolve
IP-CIDR,91.108.56.0/22,{{ rule }},no-resolve
IP-CIDR,91.108.8.0/22,{{ rule }},no-resolve
{% endmacro %}
